version: '3'
services:
    apache:
        build: .docker/apache
        container_name: test-edreams_apache
        ports:
          - 8080:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/test-edreams
        depends_on:
          - php

    php:
        build: .docker/php
        working_dir: /home/wwwroot/test-edreams
        container_name: test-edreams_php
        volumes:
          - .:/home/wwwroot/test-edreams
